# Site settings
title: Techie phil thoughts
email: 18wongj@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the site for my tech thoughts. Right now it discusses HTML, CSS, JAVASCRIPT, and some other tech languages plus some flaws and bonuses. It may occasionally engage in the philisophical or get really off-track. 
baseurl: "/bloggdr" # the subpath of your site, e.g. /blog/
url: "http://jonw27.github.io" # the base hostname & protocol for your site
twitter_username: NaN
github_username:  jonw27
highlighter: pygments


# Build settings
markdown: kramdown
